apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: t5kddcjhk-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-23800c5ca1.82z5.p3.openshiftapps.com/rhtap/rhtap-qe:568c29152874fbd582b090c21dd1cde25642d225@sha256:b23f8ae0503270a87a430359374ce5e89a84ce53ff2e2f34dca84be9a35529bc
        name: container-image  
